name: Merge SBDBEL
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Merge modules
      run: |
       wget https://github.com/ontodev/robot/raw/master/bin/robot
       wget https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar
       sh robot merge --input src/ontology/sbdbel-core.owl \
        annotate 
          --ontology-iri www.jmillanacosta.com/sbdbel/src/ontology/sbdbel.owl \
          --annotation dc:title "Safe by Design Biological Expression Language"
          --annotation dc:description "SBDBEL provides classes and properties used to model the biological relationships relevant to safe by design assessments." .
        --annotate-derived-from true \ 
        --output src/ontology/sbdbel.owl
       rm robot*
    - name: Commit files
      if: always()
      run: |
        git pull
        git add src/ontology/*
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Check if there are changes to commit
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit."
        else
            git commit -m "Actions - merge" src/ontology/* || true
          fi
        
        # Check if there are changes to push
        if [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]]; then
          if [ -n "$(git cherry -v)" ]; then
            git push || echo "Push failed."
          else
            echo "No changes to push."
          fi
        fi
